spring.application.name=worker-service
server.port=8081
# PostgreSQL - Added the timezone option here as well
spring.datasource.url=jdbc:postgresql://postgres:5432/jobqueue
spring.datasource.username=postgres
spring.datasource.password=password

spring.redis.host=redis
spring.redis.port=6379

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=0
spring.jpa.open-in-view=false